INSERT INTO echo_glyph_records (name, resonance_type, linked_nodes, glyph_image_url, notes) VALUES
('Cosmic Harmony', 'celestial', ARRAY['lunar_cycle', 'stellar_alignment'], 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400', 'A glyph representing the harmony between cosmic forces and earthly consciousness'),
('Sacred Geometry', 'geometric', ARRAY['golden_ratio', 'fibonacci_spiral'], 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400', 'Ancient patterns that reveal the mathematical foundation of reality'),
('Elemental Flow', 'elemental', ARRAY['earth_energy', 'water_wisdom', 'fire_transformation', 'air_clarity'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'The dynamic interplay of the four classical elements'),
('Chakra Resonance', 'energetic', ARRAY['root_grounding', 'heart_opening', 'crown_connection'], 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400', 'Energy centers that align consciousness with universal flow'),
('Lunar Wisdom', 'lunar', ARRAY['new_moon_intention', 'full_moon_release'], 'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=400', 'The cyclical wisdom of lunar phases guiding inner transformation'),
('Crystal Matrix', 'crystalline', ARRAY['quartz_amplification', 'amethyst_clarity', 'rose_quartz_love'], 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400', 'Crystalline structures that amplify and focus consciousness'),
('Tree of Life', 'organic', ARRAY['root_system', 'trunk_stability', 'branch_expansion'], 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400', 'The sacred tree connecting earth and sky, matter and spirit'),
('Spiral Evolution', 'evolutionary', ARRAY['growth_spiral', 'consciousness_expansion'], 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400', 'The spiral path of consciousness evolution and personal growth'),
('Unity Mandala', 'unified', ARRAY['center_point', 'radiating_patterns', 'infinite_connection'], 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400', 'A mandala representing the unity of all existence'),
('Phoenix Rising', 'transformational', ARRAY['death_cycle', 'rebirth_energy', 'transformation_fire'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'The eternal cycle of death and rebirth leading to higher consciousness');
