name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build --prefix frontend

      - name: Build Backend
        run: npm run build --prefix backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Hosting
        run: |
          # Example for deploying backend using a host like AWS
          aws s3 sync backend/dist s3://my-bucket/backend --delete
          
          # Example for deploying frontend
          aws s3 sync frontend/dist s3://my-bucket/frontend --delete
